import { StyleSheet } from "react-native"

export const getStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.card,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: theme.text,
    textAlign: "center",
  },
  headerRight: {
    width: 40,
    alignItems: "flex-end",
  },
  listContent: {
    padding: 16,
    paddingBottom: 40,
  },
  pageIntro: {
    marginBottom: 20,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: theme.text,
    marginBottom: 8,
  },
  pageDesc: {
    fontSize: 14,
    color: theme.textSecondary,
    lineHeight: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.background,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 48,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    color: theme.text,
    fontSize: 15,
  },
  tabsContainer: {
    flexDirection: "row",
    marginBottom: 16,
    backgroundColor: theme.background,
    borderRadius: 8,
    padding: 4,
    borderWidth: 1,
    borderColor: theme.border,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 6,
  },
  tabBtnActive: {
    backgroundColor: theme.primary,
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.textSecondary,
  },
  tabBtnTextActive: {
    color: "#ffffff",
  },
  categoriesScroll: {
    marginBottom: 16,
  },
  catChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border,
    marginRight: 8,
  },
  catChipActive: {
    backgroundColor: theme.primary + "20",
    borderColor: theme.primary,
  },
  catChipText: {
    fontSize: 14,
    color: theme.textSecondary,
  },
  catChipTextActive: {
    color: theme.primary,
    fontWeight: "600",
  },
  topicCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  topicCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  taskBadge1: {
    backgroundColor: "#eff6ff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 8,
  },
  taskBadge1Text: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "700",
  },
  taskBadge2: {
    backgroundColor: "#fdf4ff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 8,
  },
  taskBadge2Text: {
    color: "#c026d3",
    fontSize: 12,
    fontWeight: "700",
  },
  topicCategory: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: "600",
  },
  topicPrompt: {
    fontSize: 15,
    color: theme.text,
    lineHeight: 22,
    marginBottom: 16,
  },
  topicFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 12,
  },
  topicCount: {
    fontSize: 13,
    color: theme.textSecondary,
    flexDirection: "row",
    alignItems: "center",
  },
  topicAction: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.primary,
  },
  loaderContainer: {
    padding: 40,
    alignItems: "center",
  },
  emptyState: {
    padding: 40,
    alignItems: "center",
  },
  emptyText: {
    fontSize: 15,
    color: theme.textSecondary,
    textAlign: "center",
  },
  // Detail styles
  detailScroll: {
    flex: 1,
  },
  detailContent: {
    padding: 16,
    paddingBottom: 40,
  },
  promptCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.border,
  },
  promptHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  promptLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.textSecondary,
    textTransform: "uppercase",
  },
  promptMetaChip: {
    fontSize: 12,
    color: theme.textSecondary,
    backgroundColor: theme.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  promptText: {
    fontSize: 16,
    color: theme.text,
    lineHeight: 24,
    fontWeight: "500",
  },
  promptImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginTop: 16,
  },
  chartDescBox: {
    backgroundColor: theme.background,
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    borderLeftWidth: 4,
    borderLeftColor: theme.primary,
  },
  chartDescTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.text,
    marginBottom: 8,
  },
  bandFilterScroll: {
    marginBottom: 20,
  },
  bandBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    marginRight: 8,
  },
  essayCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.text,
    marginBottom: 16,
    marginTop: 8,
  },
  sectionNumber: {
    color: theme.primary,
  },
  analysisBox: {
    backgroundColor: theme.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  outlineTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.text,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 15,
    color: theme.text,
    lineHeight: 24,
    marginBottom: 8,
  },
  scoreRow: {
    marginBottom: 12,
  },
  scoreInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  scoreLabel: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: "500",
  },
  scoreVal: {
    fontSize: 13,
    color: theme.text,
    fontWeight: "700",
  },
  progressTrack: {
    height: 6,
    backgroundColor: theme.border,
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
  },
  feedbackCol: {
    marginTop: 16,
    padding: 12,
    borderRadius: 8,
  },
  feedbackTitle: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 8,
  },
  feedbackItem: {
    fontSize: 14,
    color: theme.text,
    lineHeight: 22,
    marginBottom: 4,
  },
  essayHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  wordCountBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  wordCountText: {
    fontSize: 12,
    color: theme.textSecondary,
    marginLeft: 4,
    fontWeight: "600",
  },
  translationBox: {
    backgroundColor: theme.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  vocabTable: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 8,
    overflow: "hidden",
  },
  vocabRow: {
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    padding: 12,
  },
  vocabPhrase: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.primary,
    marginBottom: 4,
  },
  vocabMeaning: {
    fontSize: 14,
    color: theme.text,
    marginBottom: 4,
  },
  vocabContext: {
    fontSize: 13,
    color: theme.textSecondary,
    fontStyle: "italic",
  },
})
