import { StyleSheet, Platform } from "react-native"

export const getStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    flex: 1,
  },
  headerRight: {
    padding: 4,
  },
  tabsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: theme.backgroundAlt,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  tabButtonActive: {
    backgroundColor: theme.secondary + '15',
    borderColor: theme.secondary,
  },
  tabButtonText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  tabButtonTextActive: {
    color: theme.secondary,
    fontWeight: "700",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: theme.textSecondary,
    fontSize: 14,
    marginTop: 12,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  listContainer: {
    gap: 12,
  },
  heroBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: theme.backgroundAlt,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 4,
  },
  heroBadgeText: {
    color: theme.text,
    fontSize: 13,
    fontWeight: "600",
  },
  itemCard: {
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  itemCardExpanded: {
    borderColor: theme.secondary,
  },
  cardHeaderTrigger: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    justifyContent: "space-between",
  },
  cardHeaderTitleCol: {
    flex: 1,
    paddingRight: 16,
  },
  itemTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  itemSubtitle: {
    color: theme.textSecondary,
    fontSize: 12,
  },
  formulaText: {
    color: theme.secondary,
    fontSize: 13,
    fontWeight: "600",
  },
  cardBody: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  divider: {
    height: 1,
    backgroundColor: theme.border,
    marginBottom: 16,
  },
  sectionLabel: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  explanationText: {
    color: theme.text,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  examplesContainer: {
    marginTop: 8,
  },
  exampleBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
    paddingLeft: 4,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.warning,
    marginTop: 8,
    marginRight: 10,
  },
  exampleBulletText: {
    flex: 1,
    color: theme.text,
    fontSize: 13,
    lineHeight: 18,
    fontStyle: "italic",
  },
  formulaBox: {
    backgroundColor: theme.secondary + '08',
    borderWidth: 1,
    borderColor: theme.secondary + '20',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginBottom: 16,
  },
  formulaBoxText: {
    color: theme.secondary,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontSize: 14,
    fontWeight: "700",
  },
  mistakeBlock: {
    marginBottom: 16,
  },
  mistakeHeading: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 12,
  },
  errorSideRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
    backgroundColor: theme.backgroundAlt,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  errorSideIcon: {
    flexShrink: 0,
  },
  errorWrongText: {
    flex: 1,
    color: theme.error,
    fontSize: 13,
    fontStyle: "italic",
  },
  errorCorrectText: {
    flex: 1,
    color: theme.success,
    fontSize: 13,
    fontWeight: "600",
  },
  mistakeExplainBox: {
    backgroundColor: theme.backgroundAlt,
    borderLeftWidth: 3,
    borderLeftColor: theme.secondary,
    padding: 10,
    borderRadius: 8,
    marginTop: 6,
  },
  mistakeExplainLabel: {
    color: theme.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  mistakeExplainText: {
    color: theme.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  subDivider: {
    height: 1,
    backgroundColor: theme.border,
    marginVertical: 16,
  }
})
