import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    flex: 1,
  },
  headerRight: {
    padding: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "800",
    marginTop: 20,
    marginBottom: 8,
  },
  loadingDesc: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  introCard: {
    backgroundColor: "rgba(30, 41, 59, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  badgeText: {
    color: "#60a5fa",
    fontSize: 10,
    fontWeight: "800",
  },
  introTitle: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 8,
  },
  introDesc: {
    color: "#cbd5e1",
    fontSize: 14,
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: "rgba(30, 41, 59, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  sectionLabel: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 16,
  },
  focusRow: {
    flexDirection: "row",
    gap: 12,
  },
  focusCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.02)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  focusCardActive: {
    backgroundColor: "rgba(59, 130, 246, 0.08)",
    borderColor: "#3b82f6",
  },
  focusIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  focusIconBgActive: {
    backgroundColor: "#3b82f6",
  },
  focusTitle: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 4,
  },
  focusDesc: {
    color: "#64748b",
    fontSize: 11,
  },
  selectorPairRow: {
    flexDirection: "row",
    gap: 16,
  },
  selectorCol: {
    flex: 1,
  },
  levelLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  levelLabel: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "700",
  },
  levelScroll: {
    paddingVertical: 4,
    gap: 8,
  },
  levelButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  levelButtonSelected: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderColor: "#3b82f6",
  },
  levelButtonSelectedTarget: {
    backgroundColor: "rgba(251, 191, 36, 0.15)",
    borderColor: "#fbbf24",
  },
  levelButtonText: {
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "700",
  },
  levelButtonTextSelected: {
    color: "#ffffff",
  },
  skillAdjustRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.02)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    marginBottom: 10,
  },
  skillHeaderCol: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  skillLabelText: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  skillController: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  adjustBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  adjustBtnText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  skillValBox: {
    width: 44,
    height: 32,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  skillValText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  submitBtnWrap: {
    marginTop: 8,
    borderRadius: 16,
    overflow: "hidden",
  },
  submitBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    gap: 10,
  },
  submitBtnText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  }
})
