import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  backButton: {
    padding: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  backButtonText: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 4,
  },
  headerTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    flex: 1,
  },
  scrollContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: "rgba(30, 41, 59, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
  },
  tagGroup: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  badgeHistory: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 8,
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "800",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "600",
  },
  title: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 10,
  },
  desc: {
    color: "#cbd5e1",
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 24,
  },
  historyList: {
    gap: 12,
  },
  historyCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#3b82f6",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
  },
  examinerName: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dateText: {
    color: "#94a3b8",
    fontSize: 12,
  },
  cardRight: {
    alignItems: "flex-end",
    marginLeft: 12,
  },
  scoreBadge: {
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 8,
  },
  scoreLabel: {
    color: "#3b82f6",
    fontSize: 8,
    fontWeight: "800",
  },
  scoreValue: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  viewDetailsBtn: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  viewDetailsBtnText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 20,
  },
  startPracticeBtn: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    gap: 8,
  },
  startPracticeBtnText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "700",
  },
  // Skeleton styling
  skeletonCard: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  skeletonCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    marginRight: 12,
  },
  skeletonLines: {
    flex: 1,
    gap: 8,
  },
  skeletonLineShort: {
    width: "40%",
    height: 12,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  skeletonLineLong: {
    width: "70%",
    height: 10,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  errorCard: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.2)",
    borderRadius: 12,
    padding: 16,
    color: "#f87171",
    fontSize: 14,
    marginBottom: 16,
    textAlign: "center",
  },

  // Detail View styles
  detailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  dateTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 6,
  },
  dateTagText: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "600",
  },
  reportHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  reportBadge: {
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 8,
  },
  reportBadgeText: {
    color: "#60a5fa",
    fontSize: 10,
    fontWeight: "800",
  },
  reportTitle: {
    color: "#f8fafc",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 4,
  },
  reportSub: {
    color: "#94a3b8",
    fontSize: 12,
  },
  overallBandGroup: {
    alignItems: "center",
    backgroundColor: "#1e293b",
    borderWidth: 2,
    borderColor: "#3b82f6",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 70,
  },
  overallBandLabel: {
    color: "#3b82f6",
    fontSize: 8,
    fontWeight: "800",
  },
  overallBandValue: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "800",
  },
  sectionTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 16,
  },
  subMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 10,
  },
  metricCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    width: "48%",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  subMetricName: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 4,
  },
  subMetricVal: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  transcriptBox: {
    maxHeight: 280,
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    borderRadius: 16,
    padding: 12,
    marginBottom: 24,
  },
  transcriptScrollContent: {
    paddingBottom: 12,
  },
  chatBubble: {
    padding: 12,
    borderRadius: 16,
    maxWidth: "85%",
    marginBottom: 12,
  },
  bubbleAi: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
    alignSelf: "flex-start",
  },
  bubbleUser: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.2)",
    alignSelf: "flex-end",
  },
  bubbleAuthor: {
    color: "#3b82f6",
    fontSize: 10,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  bubbleText: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
  },
  mispronouncedText: {
    color: "#f87171",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  correctionsSection: {
    marginTop: 8,
  },
  correctionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  correctionsMainTitle: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "700",
  },
  corrCard: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderLeftWidth: 4,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  corrTypeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  corrTypeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  corrOriginal: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  corrCorrection: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  corrExplanation: {
    color: "#cbd5e1",
    fontSize: 12,
    lineHeight: 16,
  },
  corrBold: {
    fontWeight: "700",
  },
  noCorrectionsText: {
    color: "#94a3b8",
    fontSize: 13,
    textAlign: "center",
    marginVertical: 12,
  },
})
