import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    flex: 1,
  },
  headerRight: {
    padding: 4,
  },
  tabsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  tabButtonActive: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderColor: "#3b82f6",
  },
  tabButtonText: {
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "600",
  },
  tabButtonTextActive: {
    color: "#3b82f6",
    fontWeight: "700",
  },
  searchBarWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 14,
  },
  body: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingSpinner: {},
  loadingText: {
    color: "#cbd5e1",
    fontSize: 14,
    marginTop: 12,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  topicsGrid: {
    gap: 12,
  },
  topicCard: {
    backgroundColor: "rgba(30, 41, 59, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 16,
  },
  topicCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  topicCardTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "700",
  },
  progressBarBg: {
    height: 6,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 3,
    marginBottom: 10,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#3b82f6",
    borderRadius: 3,
  },
  topicCardMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topicCardCount: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "600",
  },
  detailHero: {
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  detailTopicTitle: {
    color: "#f8fafc",
    fontSize: 24,
    fontWeight: "800",
  },
  detailTopicStats: {
    color: "#94a3b8",
    fontSize: 13,
    marginTop: 4,
  },
  wordCard: {
    backgroundColor: "rgba(30, 41, 59, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  wordHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  wordSpelling: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  wordPhonetics: {
    color: "#3b82f6",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 2,
  },
  bookmarkButton: {
    padding: 4,
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: 12,
  },
  meaningLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  wordMeaning: {
    color: "#f8fafc",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  exampleLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  wordExample: {
    color: "#94a3b8",
    fontSize: 13,
    fontStyle: "italic",
    lineHeight: 18,
    marginBottom: 12,
  },
  synonymsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  synonymsLabel: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "600",
  },
  wordSynonyms: {
    color: "#34d399",
    fontSize: 12,
    fontWeight: "700",
  },
  notebookBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  topicBadge: {
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  topicBadgeText: {
    color: "#60a5fa",
    fontSize: 10,
    fontWeight: "700",
  },
  flashcardsContainer: {
    flex: 1,
    padding: 16,
    justifyContent: "center",
  },
  flashcardView: {
    alignItems: "center",
    gap: 24,
  },
  flashcard: {
    width: width - 48,
    height: 380,
    borderRadius: 24,
    overflow: "hidden",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  flashcardFlipped: {},
  flashcardGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  cardSide: {
    alignItems: "center",
    justifyContent: "center",
  },
  cardIcon: {
    marginBottom: 24,
  },
  cardSpelling: {
    color: "#ffffff",
    fontSize: 32,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 8,
  },
  cardPhonetics: {
    color: "#93c5fd",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 40,
  },
  cardMeaning: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 16,
  },
  cardExample: {
    color: "#94a3b8",
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 40,
  },
  tapToFlipText: {
    color: "#475569",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  flashcardControls: {
    width: "100%",
    alignItems: "center",
  },
  nextCardButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
    gap: 8,
    elevation: 2,
  },
  nextCardButtonText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "700",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    gap: 16,
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  }
})
