import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

export const getStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    flex: 1,
  },
  headerRight: {
    padding: 4,
  },
  tabsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: theme.backgroundAlt,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.border,
  },
  tabButtonActive: {
    backgroundColor: theme.primary + '15',
    borderColor: theme.primary,
  },
  tabButtonText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  tabButtonTextActive: {
    color: theme.primary,
    fontWeight: "700",
  },
  searchBarWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.backgroundAlt,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: theme.text,
    fontSize: 14,
  },
  body: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingSpinner: {},
  loadingText: {
    color: theme.textSecondary,
    fontSize: 14,
    marginTop: 12,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  topicsGrid: {
    gap: 12,
  },
  topicCard: {
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  topicCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  topicCardTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "700",
  },
  progressBarBg: {
    height: 6,
    backgroundColor: theme.border,
    borderRadius: 3,
    marginBottom: 10,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: theme.primary,
    borderRadius: 3,
  },
  topicCardMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topicCardCount: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  detailHero: {
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  detailTopicTitle: {
    color: theme.text,
    fontSize: 24,
    fontWeight: "800",
  },
  detailTopicStats: {
    color: theme.textSecondary,
    fontSize: 13,
    marginTop: 4,
  },
  wordCard: {
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  wordHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  wordSpelling: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "800",
  },
  wordPhonetics: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 2,
  },
  bookmarkButton: {
    padding: 4,
  },
  divider: {
    height: 1,
    backgroundColor: theme.border,
    marginVertical: 12,
  },
  meaningLabel: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  wordMeaning: {
    color: theme.text,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  exampleLabel: {
    color: theme.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  wordExample: {
    color: theme.textSecondary,
    fontSize: 13,
    fontStyle: "italic",
    lineHeight: 18,
    marginBottom: 12,
  },
  synonymsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  synonymsLabel: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  wordSynonyms: {
    color: theme.success,
    fontSize: 12,
    fontWeight: "700",
  },
  notebookBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  topicBadge: {
    backgroundColor: theme.primary + '12',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  topicBadgeText: {
    color: theme.primary,
    fontSize: 10,
    fontWeight: "700",
  },
  flashcardsContainer: {
    flex: 1,
    padding: 16,
    justifyContent: "center",
  },
  flashcardView: {
    alignItems: "center",
    gap: 24,
  },
  flashcard: {
    width: width - 48,
    height: 380,
    borderRadius: 24,
    overflow: "hidden",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  flashcardFlipped: {},
  flashcardGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  cardSide: {
    alignItems: "center",
    justifyContent: "center",
  },
  cardIcon: {
    marginBottom: 24,
  },
  cardSpelling: {
    color: "#ffffff",
    fontSize: 32,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 8,
  },
  cardPhonetics: {
    color: "#93c5fd",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 40,
  },
  cardMeaning: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 16,
  },
  cardExample: {
    color: "#cbd5e1",
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 40,
  },
  tapToFlipText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  flashcardControls: {
    width: "100%",
    alignItems: "center",
  },
  nextCardButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.primary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
    gap: 8,
    elevation: 2,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  nextCardButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    gap: 16,
  },
  emptyText: {
    color: theme.textSecondary,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  bandFiltersWrapper: {
    paddingVertical: 12,
  },
  bandFiltersScroll: {
    paddingHorizontal: 16,
    gap: 8,
  },
  bandFilterButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.backgroundAlt,
  },
  bandFilterButtonActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  bandFilterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  bandFilterButtonTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
})
