import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  card: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
  },
  headerStatusWrap: {
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  statusLive: {
    backgroundColor: "rgba(16, 185, 129, 0.12)",
  },
  statusOffline: {
    backgroundColor: "rgba(167, 139, 250, 0.12)",
  },
  statusBadgeText: {
    color: "#f8fafc",
    fontSize: 10,
    fontWeight: "700",
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 10,
  },
  desc: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 16,
  },
  startCallButtonWrap: {
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
  },
  startCallButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    gap: 10,
  },
  startCallButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  fullScreenOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  pulseRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
  },
  avatarDialWrap: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#3b82f6",
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  avatarDialText: {
    color: "#ffffff",
    fontSize: 40,
    fontWeight: "800",
  },
  dialName: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 8,
  },
  dialStatus: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 1.5,
    marginBottom: 60,
  },
  circleButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  circleButtonSmall: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    justifyContent: "center",
    alignItems: "center",
  },
  hangUpButton: {
    backgroundColor: "#ef4444",
  },
  submitButton: {
    backgroundColor: "#10b981",
  },
  controlActive: {
    backgroundColor: "#ef4444",
    borderColor: "#ef4444",
  },
  activeCallContainer: {
    flex: 1,
    padding: 20,
    justifyContent: "space-between",
  },
  callHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  speakingIndicatorRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 8,
  },
  speakingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#64748b",
  },
  speakingDotActive: {
    backgroundColor: "#10b981",
  },
  speakingDotThinking: {
    backgroundColor: "#f59e0b",
  },
  speakingStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  timerText: {
    fontSize: 16,
    fontWeight: "700",
  },
  callerProfile: {
    alignItems: "center",
    marginVertical: 12,
  },
  miniAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#3b82f6",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  miniAvatarText: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "700",
  },
  callerName: {
    fontSize: 18,
    fontWeight: "800",
  },
  callerAccent: {
    fontSize: 12,
  },
  waveformContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    height: 48,
  },
  waveBar: {
    width: 6,
    height: 24,
    borderRadius: 3,
    backgroundColor: "#3b82f6",
  },
  chatScroll: {
    flex: 1,
    marginVertical: 16,
    borderRadius: 16,
    padding: 12,
  },
  chatScrollContent: {
    paddingBottom: 20,
  },
  chatBubble: {
    padding: 12,
    borderRadius: 16,
    maxWidth: "85%",
    marginBottom: 12,
  },
  bubbleAi: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
    alignSelf: "flex-start",
  },
  bubbleUser: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.2)",
    alignSelf: "flex-end",
  },
  bubbleAuthor: {
    color: "#3b82f6",
    fontSize: 10,
    fontWeight: "800",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  bubbleText: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
  },
  controlsBar: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginBottom: 12,
  },
  thinkingDesc: {
    color: "#94a3b8",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    paddingHorizontal: 24,
    marginTop: 12,
  },
  reportHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  completedBadge: {
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 8,
  },
  completedBadgeText: {
    color: "#34d399",
    fontSize: 10,
    fontWeight: "800",
  },
  reportTitle: {
    fontSize: 20,
    fontWeight: "800",
  },
  reportSub: {
    color: "#94a3b8",
    fontSize: 12,
  },
  overallScoreBox: {
    width: 72,
    height: 72,
    borderRadius: 16,
    backgroundColor: "#1e293b",
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  overallLabel: {
    color: "#3b82f6",
    fontSize: 9,
    fontWeight: "800",
  },
  overallScoreText: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "800",
  },
  subMetricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 10,
  },
  metricCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    width: "48%",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  subMetricName: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 4,
  },
  subMetricVal: {
    fontSize: 18,
    fontWeight: "800",
  },
  correctionsSection: {
    marginTop: 8,
  },
  correctionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  correctionsMainTitle: {
    fontSize: 15,
    fontWeight: "700",
  },
  corrCard: {
    backgroundColor: "rgba(255,255,255,0.02)",
    borderLeftWidth: 4,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  corrTypeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  corrTypeText: {
    fontSize: 11,
    fontWeight: "800",
    borderColor: "transparent",
  },
  corrOriginal: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  corrCorrection: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  corrExplanation: {
    color: "#cbd5e1",
    fontSize: 12,
    lineHeight: 16,
  },
  corrBold: {
    fontWeight: "700",
  },
  restartButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 16,
    gap: 8,
  },
  restartButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  noCorrectionsText: {
    fontSize: 13,
    fontStyle: 'italic',
  }
});
